name: Build and Push to ECR

on:
  pull_request:
    branches:
      - main
    types:
      - closed # Only triggers when the pull request is merged to main

jobs:
  build:
    if: github.event.pull_request.merged == true # Only if the PR was merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891855313009.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker image (WebApp) # Image changes here
        run: |
          docker build -t -f ../laks_repo/Dockerfile . 
          docker tag webapp:latest 891855313009.dkr.ecr.us-east-1.amazonaws.com/webapp:latest

      - name: Build and Push Docker image (MYSQL) # Image changes here
        run: |
          docker build -t mysql -f ../laks_repo/Dockerfile_mysql . 
          docker tag mysql:latest 891855313009.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
          docker push 891855313009.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
