name: Deploy to ECR

on:
  pull_request:
    branches:
      - main
    types:
      - closed  # Only triggers when the pull request is merged to main

jobs:
  
  build:
    
    name: Build Image
    if: github.event.pull_request.merged == true  # Only if the PR was merged
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}  # Include session token if using temporary credentials
        AWS_REGION: us-east-1  # Adjust if your region is different

    - name: Build and Push Docker image (WebApp)
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: webapp  # Update to your repository name
        IMAGE_TAG: v0.2
      run: |
        cd laks_repo  # Adjust the directory to where the Dockerfile is located
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Build and Push Docker image (MYSQL)
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mysql-db  # Update to your MySQL repository name
        IMAGE_TAG: v0.1
      run: |
        cd laks_repo  # Adjust the directory to where the Dockerfile is located
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile_mysql .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
# Nothing changed just need to push this line to reflect a change and trigger image build process so i can complete CLO835 assignment also changed aws credentials for the repo
